version: '3.8'
services: 
  postgres:
    image: "postgres"
    env_file:
      - database.env
    ports: 
      - "5432:5432"
    volumes: 
      - ./sql/:/docker-entrypoint-initdb.d

  wallet:
    image: "brucedominguez/web-api-healthcheck:latest"
    restart: on-failure
    env_file:
      - database.env
    ports:
      - "8080:8080"
    depends_on: 
      - "postgres"